### ISSUE TITLE
Add support for NetCDF

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#24]
Test file: https://github.com/o2r-project/geoextent/blob/master/tests/testdata/ECMWF_ERA-40_subset1.nc

- [x] geospatial extent implemented (+ tests)
- [ ] temporal extent implemented (+ tests)

**Comment by nuest** [comment]
https://pypi.org/project/netCDF4/

**Comment by SbastianGarzon** [comment]
This could be relevant : 
https://gdal.org/drivers/raster/netcdf.html#georeference
_"There is no universal way of storing georeferencing in NetCDF files. The driver first tries to follow the CF-1 Convention from UNIDATA looking for the Metadata named “grid_mapping”. If “grid_mapping” is not present, the driver will try to find an lat/lon grid array to set geotransform array. The NetCDF driver verifies that the Lat/Lon array is equally space."_

GDAL is already trying to extract the CRS. This means that since #99, NETCDF files are supported (BBOX).

**Comment by SbastianGarzon** [comment]
Issue closed (spatial extent extraction), extraction of the temporal extent will be handle by #123
